export const BULLET_REMOVAL_TIMEOUT = 1000
export const RAGDOLL_REMOVAL_TIMEOUT = 5000
export const BULLET_FORCE = 0.015
export const BULLET_IMPACT = 0.075
export const BULLET_FORCE_MULTIPLIER = 10
export const ENEMY_BULLET_FORCE = 0.025
