export const BULLET_REMOVAL_TIMEOUT = 1000
export const RAGDOLL_REMOVAL_TIMEOUT = 5000
export const BULLET_FORCE = 0.015
export const BULLET_IMPACT = 0.075
export const BULLET_FORCE_MULTIPLIER = 10

// Enemy Actions Constants
export const ENEMY_BULLET_FORCE = 0.025
export const ENEMY_BULLET_SHOOT_INTERVAL_MIN = 500
export const ENEMY_BULLET_SHOOT_INTERVAL_MAX = 3000
export const ENEMY_CROUCH_INTERVAL_MIN = 3000
export const ENEMY_CROUCH_INTERVAL_MAX = 10000
export const ENEMY_JUMP_INTERVAL_MIN = 3000
export const ENEMY_JUMP_INTERVAL_MAX = 10000
